import { OnInit, QueryList, EventEmitter, AfterContentInit, SimpleChanges, OnChanges, OnDestroy } from '@angular/core';
import { DataGroupComponent } from './components/data-group.component';
export declare class DataGroupsComponent implements OnInit, AfterContentInit, OnChanges, OnDestroy {
    class: string;
    model: any;
    group: string;
    enctype: string;
    multiple: boolean;
    highlightOnValid: boolean;
    autocomplete: boolean;
    submitEvent: EventEmitter<any>;
    dataGroupComponents: QueryList<DataGroupComponent>;
    private _model;
    private modelMap;
    private modelResetSubscriptions$;
    private firstMount;
    ngOnInit(): void;
    ngAfterContentInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    private addModelResetSubscription;
    private unsubscribeAllModelResetSubscriptions;
    private initBaseModel;
    private subscribeToBaseModelArrayChanges;
    private refreshBaseModelArray;
    private unsubscribeToBaseModelArrayChanges;
    private initModelMap;
    private generateModelMap;
    private applyToAllModelMap;
    private applyModelMap;
    private subscribeToModelReset;
    private applyToAllModelPropertiesMap;
    private applyModelPropertiesMap;
    private listenDataGroupsListChanges;
    private listenDataInputsListChanges;
    submitData(): void;
    private parseValidationResult;
    private groupMultipleValidationResult;
    private generateFormData;
    private formatErrors;
    private manageErrors;
    private setDataInputComponentError;
    private unsubscribeAll;
    ngOnDestroy(): void;
}
