import { AfterViewInit, ElementRef, EventEmitter, DoCheck } from '@angular/core';
import { DataInputBase } from '../common/classes/data-input-base';
export declare class BsDatepickerComponent extends DataInputBase implements AfterViewInit, DoCheck {
    class: string;
    hostId: string;
    inputElementRef: ElementRef;
    configs: {
        [key: string]: string;
    };
    autoclose: boolean;
    calendarWeeks: boolean;
    clearBtn: boolean;
    datesDisabled: Array<string> | string;
    daysOfWeekDisabled: Array<string> | string;
    daysOfWeekHighlighted: Array<string> | string;
    defaultViewDate: string;
    disableTouchKeyboard: boolean;
    enableOnReadonly: boolean;
    endDate: string;
    forceParse: boolean;
    format: string;
    immediateUpdates: boolean;
    keyboardNavigation: boolean;
    maxViewMode: string;
    minViewMode: string;
    multidate: boolean | number;
    multidateSeparator: string;
    orientation: string;
    showOnFocus: boolean;
    startDate: string;
    startView: string;
    showWeekDays: boolean;
    title: string;
    todayBtn: boolean;
    todayHighlight: boolean;
    weekStart: number;
    zIndexOffset: number;
    utc: boolean;
    autocomplete: boolean;
    showEvent: EventEmitter<any>;
    hideEvent: EventEmitter<any>;
    clearDateEvent: EventEmitter<any>;
    changeDateEvent: EventEmitter<any>;
    changeMonthEvent: EventEmitter<any>;
    changeYearEvent: EventEmitter<any>;
    changeDecadeEvent: EventEmitter<any>;
    changeCenturyEvent: EventEmitter<any>;
    private datepicker;
    private datepickerConfigs;
    private watchedProperties;
    setConfigsOnInit(): void;
    ngAfterViewInit(): void;
    bindFocusoutEvents(event: any): any;
    detectPropertiesChanges(propName: string): void;
    ngDoCheck(): void;
    bindWatchModelEvents(): void;
    initSelectedDate(): void;
    initJQueryEl(): void;
    initDatepicker(): void;
    buildDatepickerConfigs(): void;
    setDatepickerConfigsOverrides(): void;
    bindEventsToDatepicker(): void;
    getValue(): any;
    setValue(): void;
    setDate(value: any): void;
    setDates(value: any): void;
    getDate(): any;
    getDates(): any;
    refreshDatepicker(): void;
    refresh(): void;
}
