import { ElementRef, AfterViewInit, DoCheck, EventEmitter } from '@angular/core';
import { DataInputBase } from '../common/classes/data-input-base';
import { SelectOption, SelectOptionGroup } from '../common/types';
export declare class BsSelectComponent extends DataInputBase implements AfterViewInit, DoCheck {
    class: string;
    selectElementRef: ElementRef;
    options: Array<SelectOption> | Array<SelectOptionGroup>;
    configs: {
        [key: string]: any;
    };
    style: string;
    styleBase: string;
    placeholder: string;
    iconBase: string;
    selectAllText: string;
    deselectAllText: string;
    liveSearch: boolean;
    multiple: boolean;
    maxOptions: number;
    maxOptionsText: string;
    selectedTextFormat: string;
    showTick: boolean;
    countSelectedText: string;
    actionsBox: boolean;
    header: string;
    dropupAuto: string;
    shownEvent: EventEmitter<Event>;
    hiddenEvent: EventEmitter<Event>;
    onValidated: boolean;
    private select;
    private onShown;
    private selectConfigs;
    private watchedProperties;
    ngAfterViewInit(): void;
    ngDoCheck(): void;
    bindWatchModelEvents(): void;
    detectPropertiesChanges(propName: string): void;
    initJQueryEl(): void;
    initSelect(): void;
    buildSelectConfigs(): void;
    setSelectConfigsOverrides(): void;
    disableSelectWhenOptionsAreEmpty(): void;
    enableOrDisableSelect(): void;
    bindEventsToSelect(): void;
    bindEventsAfterValidateField(): void;
    addAutoCloseClass(): void;
    addOrRemoveValidationClasses(): void;
    refreshSelectedOptions(): void;
    initSelectedOptions(): void;
    hideSelectAllButton(): void;
    refreshSelect(): void;
    rebuildSelect(): void;
    setOnValidated(): void;
    refresh(): void;
}
